FROM rust:1.76.0-bullseye as builder

WORKDIR /app

# Copy the Cargo.toml and Cargo.lock files to the container
COPY Cargo.toml Cargo.lock ./

# # Create an empty src directory to trick Cargo into thinking it's an existing project
RUN mkdir src && echo "fn main() {}" > ./src/main.rs

# Build dependencies (this step can be cached if Cargo.toml and Cargo.lock haven't changed)
RUN cargo build -r --locked

COPY src ./src
COPY .sqlx ./.sqlx
COPY migrations ./migrations
COPY config-prod.toml ./config-prod.toml

ARG SQLX_OFFLINE=true

RUN cargo install --locked --path .

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /usr/local/cargo/bin/server /app/server
COPY --from=builder /app/migrations /app/migrations
COPY --from=builder /app/config-prod.toml /app/config-prod.toml

CMD ["./server", "start"]
